import {
  Speaker,
  Lightbulb,
  Monitor,
  Layers,
  Utensils,
  Wine,
  GlassWater,
  Camera,
  Video,
  Mic,
  Music,
  Disc,
  Building,
  ClipboardList,
  Shield,
  Palette,
} from 'lucide-react'

export const SERVICES = [
  { id: 'sound', label: 'Som', icon: Speaker, color: 'text-blue-400', bg: 'bg-blue-500/10' },
  { id: 'light', label: 'Luz', icon: Lightbulb, color: 'text-yellow-400', bg: 'bg-yellow-500/10' },
  {
    id: 'led',
    label: 'Painel LED',
    icon: Monitor,
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
  },
  { id: 'grid', label: 'Estrutura', icon: Layers, color: 'text-gray-400', bg: 'bg-gray-500/10' },
  {
    id: 'buffet',
    label: 'Buffet',
    icon: Utensils,
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
  },
  {
    id: 'drinks',
    label: 'Bebidas',
    icon: GlassWater,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
  },
  {
    id: 'cocktails',
    label: 'Bar Drinks',
    icon: Wine,
    color: 'text-pink-400',
    bg: 'bg-pink-500/10',
  },
  { id: 'photo', label: 'Fotografia', icon: Camera, color: 'text-teal-400', bg: 'bg-teal-500/10' },
  { id: 'video', label: 'Videomaker', icon: Video, color: 'text-red-400', bg: 'bg-red-500/10' },
  { id: 'singer', label: 'Cantor', icon: Mic, color: 'text-indigo-400', bg: 'bg-indigo-500/10' },
  { id: 'band', label: 'Banda', icon: Music, color: 'text-rose-400', bg: 'bg-rose-500/10' },
  { id: 'dj', label: 'DJ', icon: Disc, color: 'text-violet-400', bg: 'bg-violet-500/10' },
  {
    id: 'space',
    label: 'Espaço',
    icon: Building,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
  },
  {
    id: 'decoracao',
    label: 'Decoração',
    icon: Palette,
    color: 'text-fuchsia-400',
    bg: 'bg-fuchsia-500/10',
  },
  {
    id: 'ceremonial',
    label: 'Cerimonial',
    icon: ClipboardList,
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
  },
  {
    id: 'security',
    label: 'Seguranças',
    icon: Shield,
    color: 'text-slate-400',
    bg: 'bg-slate-500/10',
  },
] as const
